[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg"]
cmds = ["python3 -m venv /opt/venv"]

[phases.install]
cmds = ["/opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/uvicorn tts_server_v3_only:app --host 0.0.0.0 --port $PORT"
